### ISSUE TITLE
meet error when running

### ISSUE THREAD

**Issue by Explorermomo** [CMACH508/DeepTH#1]
Hello, is the code of the project incomplete?

I got some errors while running your project.

Traceback (most recent call last):
  File "/home/wu/anaconda3/envs/CAD/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/wu/anaconda3/envs/CAD/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wu/Project_ICCAD/DeepTH-main/code/selfplay.py", line 83, in playGame
    data = np.load(fileName, allow_pickle=True).item()
  File "/home/wu/anaconda3/envs/CAD/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './processed_data/adaptec3_clustered.npy'
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    data = np.load(file, allow_pickle=True).item()
  File "/home/wu/anaconda3/envs/CAD/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './data/data0_0.npy'

Thanks.

**Comment by shiyanliang** [comment]
Hello, I would like to ask you how you started the project, my python test.py (python selfplay.py or main.py) all appear ModuleNotFoundError: No module named 'dreamplace. Params'

**Comment by Explorermomo** [comment]
maybe, you need to deploy dreamplace.Params first.

**Comment by Mathew0553** [comment]
I think The code is not fully disclosed ，it lacks of the pre-process step,such as how to  Hypergraph partitioning and get the standard cell cluster 
> FileNotFoundError: [Errno 2] No such file or directory: './processed_data/adaptec3_clustered.npy
